name: Manual build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'work branch'
        default: 'development'
        required: true
      package:
        description: 'build package'
        default: 'legend-spa'
        required: true

env:
  HOST_NAME: Earthly

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print host name
        run: echo "Host $HOST_NAME"
      - name: Print homepage URL
        run: echo "Host https://$HOST_NAME.dev"
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: build
        run: npm install octokit
      - name: diff-index
        id: diffindex
        run: git diff-index HEAD --quiet
        continue-on-error: true
      - name: commit
        if: ${{ steps.diffindex.outcome == 'failure' }}
        env:
          WORKFLOW_NAME: ${{ github.workflow }}
        run: |
          echo ${{ steps.diffindex.outcome }}
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "build" -m "from: <$WORKFLOW_NAME>"
          git push
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Print host name
        run: echo "Host $HOST_NAME"
